"""Config 기본값 상수."""

DEFAULTS: dict[str, object] = {
    "system.log_level": "INFO",
    "system.timezone": "Asia/Seoul",
    "db.path": "db/ante.db",
    "db.event_log_retention_days": 30,
    "parquet.base_path": "data/",
    "parquet.compression": "snappy",
    "web.host": "0.0.0.0",
    "web.port": 8000,
    "eventbus.history_size": 1000,
    "instrument.default_exchange": "KRX",
    "broker.commission_rate": 0.00015,
    "broker.sell_tax_rate": 0.0023,
    "broker.retry.max_retries_order": 3,
    "broker.retry.max_retries_query": 2,
    "broker.retry.max_retries_auth": 2,
    "broker.retry.backoff_base_seconds": 1.0,
    "broker.circuit_breaker.failure_threshold": 5,
    "broker.circuit_breaker.recovery_timeout": 60,
    "broker.timeout.order": 10,
    "broker.timeout.query": 5,
    "broker.timeout.auth": 10,
    "treasury.sync_interval_seconds": 300,
}
