/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/api/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 결재 목록 */
        get: operations["list_approvals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approvals/{approval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 결재 상세 */
        get: operations["get_approval"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approvals/{approval_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 승인/거부 처리 */
        patch: operations["update_approval_status"];
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 감사 로그 */
        get: operations["list_audit_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 패스워드 로그인 */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로그아웃 */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 현재 사용자 정보 */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 봇 목록 조회 */
        get: operations["list_bots"];
        put?: never;
        /** 봇 생성 */
        post: operations["create_bot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots/{bot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 봇 상세 조회 */
        get: operations["get_bot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots/{bot_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 봇 시작 */
        post: operations["start_bot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots/{bot_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 봇 중지 */
        post: operations["stop_bot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 동적 설정 조회 */
        get: operations["list_configs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 동적 설정 변경 */
        put: operations["update_config"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 데이터셋 목록 */
        get: operations["list_datasets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/feed-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feed 파이프라인 상태 */
        get: operations["get_feed_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 저장 용량 현황 */
        get: operations["get_storage_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 멤버 목록 */
        get: operations["list_members"];
        put?: never;
        /** 멤버 등록 */
        post: operations["create_member"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 멤버 상세 */
        get: operations["get_member"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/{member_id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 패스워드 변경 */
        patch: operations["change_password"];
        trace?: never;
    };
    "/api/members/{member_id}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 멤버 재활성화 */
        post: operations["reactivate_member"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/{member_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 멤버 폐기 */
        post: operations["revoke_member"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/{member_id}/rotate-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 토큰 재발급 */
        post: operations["rotate_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/{member_id}/scopes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 권한 범위 변경 */
        put: operations["update_scopes"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/{member_id}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 멤버 정지 */
        post: operations["suspend_member"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 알림 목록 */
        get: operations["list_notifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 자산 추이 */
        get: operations["get_portfolio_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/value": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 총 자산 가치 */
        get: operations["get_portfolio_value"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 리포트 목록 */
        get: operations["list_reports"];
        put?: never;
        /** 리포트 제출 */
        post: operations["submit_report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 리포트 상세 */
        get: operations["get_report"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 전략 목록 조회 */
        get: operations["list_strategies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{strategy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 전략 상세 조회 */
        get: operations["get_strategy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{strategy_id}/performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 전략 성과 지표 */
        get: operations["get_strategy_performance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{strategy_id}/performance/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 일별 성과 집계 */
        get: operations["get_daily_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{strategy_id}/performance/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 월별 성과 집계 */
        get: operations["get_monthly_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{strategy_id}/performance/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 주별 성과 집계 */
        get: operations["get_weekly_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{strategy_id}/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 전략 거래 내역 */
        get: operations["get_strategy_trades"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 전략 파일 검증 */
        post: operations["validate_strategy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 헬스체크 */
        get: operations["get_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/kill-switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 킬 스위치 제어 */
        post: operations["toggle_kill_switch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 시스템 상태 조회 */
        get: operations["get_system_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 거래 기록 목록 */
        get: operations["list_trades"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/treasury": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 자금 현황 요약 */
        get: operations["get_treasury_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/treasury/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 잔고 설정 */
        post: operations["set_balance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/treasury/bots/{bot_id}/allocate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 예산 할당 */
        post: operations["allocate_budget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/treasury/bots/{bot_id}/deallocate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 예산 회수 */
        post: operations["deallocate_budget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/treasury/budgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 봇별 예산 목록 */
        get: operations["get_budget_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/treasury/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 자금 변동 이력 */
        get: operations["get_transactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        ApprovalDetailResponse: {
            approval: {
                [key: string]: unknown;
            };
            report_detail?: {
                [key: string]: unknown;
            } | null;
        };
        ApprovalListResponse: {
            approvals: {
                [key: string]: unknown;
            }[];
            total: number;
        };
        ApprovalUpdateResponse: {
            approval: {
                [key: string]: unknown;
            };
        };
        AuditLogListResponse: {
            logs: {
                [key: string]: unknown;
            }[];
            total: number;
        };
        BalanceSetResponse: {
            total_balance: number;
            updated_at: string;
        };
        BotDetailResponse: {
            bot: {
                [key: string]: unknown;
            };
        };
        BotListResponse: {
            bots: {
                [key: string]: unknown;
            }[];
            next_cursor?: string | null;
        };
        BudgetListResponse: {
            budgets: {
                [key: string]: unknown;
            }[];
        };
        BudgetOperationResponse: {
            allocated: number;
            available: number;
            bot_id: string;
        };
        ConfigListResponse: {
            configs: {
                [key: string]: unknown;
            }[];
        };
        ConfigUpdateResponse: {
            key: string;
            new_value?: unknown;
            old_value?: unknown;
        };
        DailySummaryItem: {
            date: string;
            realized_pnl: number;
            trade_count: number;
            win_rate: number;
        };
        DailySummaryResponse: {
            items: components["schemas"]["DailySummaryItem"][];
        };
        DatasetItem: {
            data_type: string;
            end_date?: string | null;
            id: string;
            /** @default 0 */
            row_count: number;
            start_date?: string | null;
            symbol: string;
            timeframe: string;
        };
        DatasetListResponse: {
            items: components["schemas"]["DatasetItem"][];
            total: number;
        };
        EquityCurvePoint: {
            date: string;
            value: number;
        };
        ErrorResponse: {
            /** @default  */
            detail: string;
            /** @default  */
            instance: string;
            /** @default 500 */
            status: number;
            /** @default Internal Server Error */
            title: string;
            /** @default /errors/internal */
            type: string;
        };
        FeedStatusResponse: {
            /** @default [] */
            api_keys: {
                [key: string]: unknown;
            }[];
            /** @default [] */
            checkpoints: {
                [key: string]: unknown;
            }[];
            /** @default false */
            initialized: boolean;
            /** @default [] */
            recent_reports: {
                [key: string]: unknown;
            }[];
        };
        HealthResponse: {
            ok: boolean;
        };
        KillSwitchResponse: {
            changed_at: string;
            status: string;
        };
        LoginRequest: {
            member_id: string;
            password: string;
        };
        LoginResponse: {
            member_id: string;
            name: string;
            type: string;
        };
        LogoutResponse: {
            ok: boolean;
        };
        MemberCreateResponse: {
            member: {
                [key: string]: unknown;
            };
            token: string;
        };
        MemberDetailResponse: {
            member: {
                [key: string]: unknown;
            };
        };
        MemberListResponse: {
            members: {
                [key: string]: unknown;
            }[];
            total: number;
        };
        MemberScopesResponse: {
            member: {
                [key: string]: unknown;
            };
        };
        MemberTokenResponse: {
            member: {
                [key: string]: unknown;
            };
            token: string;
        };
        MeResponse: {
            /** @default  */
            emoji: string;
            /** @default  */
            login_at: string;
            member_id: string;
            name: string;
            /** @default  */
            role: string;
            type: string;
        };
        MonthlySummaryItem: {
            month: number;
            realized_pnl: number;
            trade_count: number;
            win_rate: number;
            year: number;
        };
        MonthlySummaryResponse: {
            items: components["schemas"]["MonthlySummaryItem"][];
        };
        NotificationItem: {
            created_at: string;
            id: string;
            level: string;
            message: string;
            success: boolean;
            title: string;
        };
        NotificationListResponse: {
            next_cursor?: string | null;
            notifications: components["schemas"]["NotificationItem"][];
        };
        OkResponse: {
            ok: boolean;
        };
        PortfolioHistoryPoint: {
            date: string;
            value: number;
        };
        PortfolioHistoryResponse: {
            data: components["schemas"]["PortfolioHistoryPoint"][];
            period: string;
        };
        PortfolioValueResponse: {
            daily_pnl: number;
            daily_pnl_pct: number;
            total_value: number;
            updated_at: string;
        };
        ReportDetailResponse: {
            backtest_period?: string | null;
            /** @default [] */
            equity_curve: {
                [key: string]: unknown;
            }[];
            final_balance?: number | null;
            initial_balance?: number | null;
            max_drawdown_pct?: number | null;
            /** @default {} */
            metrics: {
                [key: string]: unknown;
            };
            /** @default  */
            rationale: string;
            /** @default  */
            recommendations: string;
            report_id: string;
            reviewed_at?: string | null;
            /** @default  */
            risks: string;
            sharpe_ratio?: number | null;
            status: string;
            strategy_name: string;
            /** @default  */
            strategy_path: string;
            strategy_version: string;
            submitted_at: string;
            /** @default  */
            submitted_by: string;
            /** @default  */
            summary: string;
            /** @default [] */
            symbols: unknown[];
            total_return_pct?: number | null;
            total_trades?: number | null;
            /** @default  */
            user_notes: string;
            win_rate?: number | null;
        };
        ReportListItem: {
            report_id: string;
            status: string;
            strategy: string;
            submitted_at: string;
        };
        ReportListResponse: {
            next_cursor?: string | null;
            reports: components["schemas"]["ReportListItem"][];
        };
        ReportSubmitResponse: {
            report_id: string;
            status: string;
            strategy: string;
        };
        SeedResetResponse: {
            ok: boolean;
            scenario: string;
        };
        StatusResponse: {
            halt_reason?: string | null;
            halt_time?: string | null;
            status: string;
            trading_status?: string | null;
            /** @default 0.1.0 */
            version: string;
        };
        StorageSummaryResponse: {
            by_timeframe: {
                [key: string]: number;
            };
            total_bytes: number;
            total_mb: number;
        };
        StrategyDetailResponse: {
            bot?: {
                [key: string]: unknown;
            } | null;
            strategy: {
                [key: string]: unknown;
            };
        };
        StrategyListItem: {
            author: string;
            bot_id?: string | null;
            bot_status?: string | null;
            id: string;
            name: string;
            status: string;
            version: string;
        };
        StrategyListResponse: {
            strategies: components["schemas"]["StrategyListItem"][];
        };
        StrategyPerformanceResponse: {
            /** @default 0 */
            avg_pnl: number;
            /** @default [] */
            equity_curve: {
                [key: string]: unknown;
            }[];
            /** @default 0 */
            losing_trades: number;
            /** @default 0 */
            max_drawdown: number;
            /** @default 0 */
            profit_factor: number;
            /** @default 0 */
            sharpe_ratio: number;
            /** @default 0 */
            total_pnl: number;
            /** @default 0 */
            total_trades: number;
            /** @default 0 */
            win_rate: number;
            /** @default 0 */
            winning_trades: number;
        } & {
            [key: string]: unknown;
        };
        StrategyTradeItem: {
            bot_id: string;
            price: number;
            quantity: number;
            side: string;
            status: string;
            symbol: string;
            timestamp: string;
            trade_id: string;
        };
        StrategyTradesResponse: {
            next_cursor?: string | null;
            trades: components["schemas"]["StrategyTradeItem"][];
        };
        StrategyValidateResponse: {
            /** @default [] */
            errors: string[];
            valid: boolean;
            /** @default [] */
            warnings: string[];
        };
        TradeItem: {
            bot_id: string;
            created_at: string;
            price: number;
            quantity: number;
            side: string;
            status: string;
            symbol: string;
            trade_id: string;
        };
        TradeListResponse: {
            next_cursor?: string | null;
            trades: components["schemas"]["TradeItem"][];
        };
        TransactionItem: {
            amount: number;
            bot_id?: string | null;
            created_at: string;
            /** @default  */
            description: string;
            id: number;
            type: string;
        };
        TransactionListResponse: {
            items: components["schemas"]["TransactionItem"][];
            total: number;
        };
        TreasurySummaryResponse: {
            account_no?: string | null;
            broker_id?: string | null;
            broker_name?: string | null;
            broker_short_name?: string | null;
            /** @default 0.00015 */
            commission_rate: number;
            exchange?: string | null;
            is_virtual?: boolean | null;
            /** @default 0.0023 */
            sell_tax_rate: number;
            synced_at?: string | null;
            /** @default 0 */
            total_allocated: number;
            /** @default 0 */
            total_balance: number;
            /** @default 0 */
            total_evaluation: number;
            /** @default 0 */
            total_profit_loss: number;
            /** @default 0 */
            unallocated: number;
        } & {
            [key: string]: unknown;
        };
        WeeklySummaryItem: {
            realized_pnl: number;
            trade_count: number;
            week_end: string;
            week_label: string;
            week_start: string;
            win_rate: number;
        };
        WeeklySummaryResponse: {
            items: components["schemas"]["WeeklySummaryItem"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type ApprovalDetailResponse = components['schemas']['ApprovalDetailResponse'];
export type ApprovalListResponse = components['schemas']['ApprovalListResponse'];
export type ApprovalUpdateResponse = components['schemas']['ApprovalUpdateResponse'];
export type AuditLogListResponse = components['schemas']['AuditLogListResponse'];
export type BalanceSetResponse = components['schemas']['BalanceSetResponse'];
export type BotDetailResponse = components['schemas']['BotDetailResponse'];
export type BotListResponse = components['schemas']['BotListResponse'];
export type BudgetListResponse = components['schemas']['BudgetListResponse'];
export type BudgetOperationResponse = components['schemas']['BudgetOperationResponse'];
export type ConfigListResponse = components['schemas']['ConfigListResponse'];
export type ConfigUpdateResponse = components['schemas']['ConfigUpdateResponse'];
export type DailySummaryItem = components['schemas']['DailySummaryItem'];
export type DailySummaryResponse = components['schemas']['DailySummaryResponse'];
export type DatasetItem = components['schemas']['DatasetItem'];
export type DatasetListResponse = components['schemas']['DatasetListResponse'];
export type EquityCurvePoint = components['schemas']['EquityCurvePoint'];
export type ErrorResponse = components['schemas']['ErrorResponse'];
export type FeedStatusResponse = components['schemas']['FeedStatusResponse'];
export type HealthResponse = components['schemas']['HealthResponse'];
export type KillSwitchResponse = components['schemas']['KillSwitchResponse'];
export type LoginRequest = components['schemas']['LoginRequest'];
export type LoginResponse = components['schemas']['LoginResponse'];
export type LogoutResponse = components['schemas']['LogoutResponse'];
export type MemberCreateResponse = components['schemas']['MemberCreateResponse'];
export type MemberDetailResponse = components['schemas']['MemberDetailResponse'];
export type MemberListResponse = components['schemas']['MemberListResponse'];
export type MemberScopesResponse = components['schemas']['MemberScopesResponse'];
export type MemberTokenResponse = components['schemas']['MemberTokenResponse'];
export type MeResponse = components['schemas']['MeResponse'];
export type MonthlySummaryItem = components['schemas']['MonthlySummaryItem'];
export type MonthlySummaryResponse = components['schemas']['MonthlySummaryResponse'];
export type NotificationItem = components['schemas']['NotificationItem'];
export type NotificationListResponse = components['schemas']['NotificationListResponse'];
export type OkResponse = components['schemas']['OkResponse'];
export type PortfolioHistoryPoint = components['schemas']['PortfolioHistoryPoint'];
export type PortfolioHistoryResponse = components['schemas']['PortfolioHistoryResponse'];
export type PortfolioValueResponse = components['schemas']['PortfolioValueResponse'];
export type ReportDetailResponse = components['schemas']['ReportDetailResponse'];
export type ReportListItem = components['schemas']['ReportListItem'];
export type ReportListResponse = components['schemas']['ReportListResponse'];
export type ReportSubmitResponse = components['schemas']['ReportSubmitResponse'];
export type SeedResetResponse = components['schemas']['SeedResetResponse'];
export type StatusResponse = components['schemas']['StatusResponse'];
export type StorageSummaryResponse = components['schemas']['StorageSummaryResponse'];
export type StrategyDetailResponse = components['schemas']['StrategyDetailResponse'];
export type StrategyListItem = components['schemas']['StrategyListItem'];
export type StrategyListResponse = components['schemas']['StrategyListResponse'];
export type StrategyPerformanceResponse = components['schemas']['StrategyPerformanceResponse'];
export type StrategyTradeItem = components['schemas']['StrategyTradeItem'];
export type StrategyTradesResponse = components['schemas']['StrategyTradesResponse'];
export type StrategyValidateResponse = components['schemas']['StrategyValidateResponse'];
export type TradeItem = components['schemas']['TradeItem'];
export type TradeListResponse = components['schemas']['TradeListResponse'];
export type TransactionItem = components['schemas']['TransactionItem'];
export type TransactionListResponse = components['schemas']['TransactionListResponse'];
export type TreasurySummaryResponse = components['schemas']['TreasurySummaryResponse'];
export type WeeklySummaryItem = components['schemas']['WeeklySummaryItem'];
export type WeeklySummaryResponse = components['schemas']['WeeklySummaryResponse'];
export type $defs = Record<string, never>;
export interface operations {
    list_approvals: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: string | null;
                type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalListResponse"];
                };
            };
        };
    };
    get_approval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalDetailResponse"];
                };
            };
        };
    };
    update_approval_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalUpdateResponse"];
                };
            };
        };
    };
    list_audit_logs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogListResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    list_bots: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotListResponse"];
                };
            };
        };
    };
    create_bot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotDetailResponse"];
                };
            };
        };
    };
    get_bot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotDetailResponse"];
                };
            };
        };
    };
    start_bot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotDetailResponse"];
                };
            };
        };
    };
    stop_bot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BotDetailResponse"];
                };
            };
        };
    };
    list_configs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigListResponse"];
                };
            };
        };
    };
    update_config: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigUpdateResponse"];
                };
            };
        };
    };
    list_datasets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetListResponse"];
                };
            };
        };
    };
    get_feed_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedStatusResponse"];
                };
            };
        };
    };
    get_storage_summary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageSummaryResponse"];
                };
            };
        };
    };
    list_members: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberListResponse"];
                };
            };
        };
    };
    create_member: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberCreateResponse"];
                };
            };
        };
    };
    get_member: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberDetailResponse"];
                };
            };
        };
    };
    change_password: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    reactivate_member: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberDetailResponse"];
                };
            };
        };
    };
    revoke_member: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberDetailResponse"];
                };
            };
        };
    };
    rotate_token: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberTokenResponse"];
                };
            };
        };
    };
    update_scopes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberScopesResponse"];
                };
            };
        };
    };
    suspend_member: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberDetailResponse"];
                };
            };
        };
    };
    list_notifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationListResponse"];
                };
            };
        };
    };
    get_portfolio_history: {
        parameters: {
            query?: {
                period?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioHistoryResponse"];
                };
            };
        };
    };
    get_portfolio_value: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioValueResponse"];
                };
            };
        };
    };
    list_reports: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportListResponse"];
                };
            };
        };
    };
    submit_report: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportSubmitResponse"];
                };
            };
        };
    };
    get_report: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDetailResponse"];
                };
            };
        };
    };
    list_strategies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyListResponse"];
                };
            };
        };
    };
    get_strategy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyDetailResponse"];
                };
            };
        };
    };
    get_strategy_performance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyPerformanceResponse"];
                };
            };
        };
    };
    get_daily_summary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailySummaryResponse"];
                };
            };
        };
    };
    get_monthly_summary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlySummaryResponse"];
                };
            };
        };
    };
    get_weekly_summary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklySummaryResponse"];
                };
            };
        };
    };
    get_strategy_trades: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyTradesResponse"];
                };
            };
        };
    };
    validate_strategy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyValidateResponse"];
                };
            };
        };
    };
    get_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    toggle_kill_switch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KillSwitchResponse"];
                };
            };
        };
    };
    get_system_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    list_trades: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeListResponse"];
                };
            };
        };
    };
    get_treasury_summary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreasurySummaryResponse"];
                };
            };
        };
    };
    set_balance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceSetResponse"];
                };
            };
        };
    };
    allocate_budget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetOperationResponse"];
                };
            };
        };
    };
    deallocate_budget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetOperationResponse"];
                };
            };
        };
    };
    get_budget_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetListResponse"];
                };
            };
        };
    };
    get_transactions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionListResponse"];
                };
            };
        };
    };
}
